name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or change to your working branch

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies for testing
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run unit tests
      run: |
        cd src
        pytest test_addition.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ci-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/python-ci-app:latest
